### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by haltingstate** [odegeasslbc/FastGAN-pytorch#51]
>FileNotFoundError: [Errno 2] No such file or directory: './models/60000.pth'

For both

```
python hon eval.py --n_sample 1
```

and 

```
python eval.py --n_sample 100 --start_iter 0 --end_iter 50000
```

```
Traceback (most recent call last):
  File "/home/ml1/FastGAN-pytorch/train_results/test1/eval.py", line 67, in <module>
    checkpoint = torch.load(ckpt, map_location=lambda a,b: a)
  File "/home/ml1/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ml1/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ml1/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 211, in init
    super(_open_file, self).init(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/60000.pth'
```

Appears to be a bug. No range check?

**Comment by godisme1220** [comment]
see these lines in eval.py
`parser.add_argument('--start_iter', type=int, default=6)
 parser.add_argument('--end_iter', type=int, default=10)`
`parser.add_argument('--multiplier', type=int, default=10000, help='multiplier for model number')`

I also encounter same problem, it seems like the author want us to use the 60000 iterations .pth file, but I only train like 5000 iters.
so I change the readme.md generate image code to:
`python eval.py --start_iter 5 --end_iter 5 --multiplier 1000  --n_sample 10 `

then the bug fix, images does generated.

Best regards, Eugene.

**Comment by godisme1220** [comment]
> > FileNotFoundError: [Errno 2] No such file or directory: './models/60000.pth'
> 
> For both
> 
> ```
> python hon eval.py --n_sample 1
> ```
> 
> and
> 
> ```
> python eval.py --n_sample 100 --start_iter 0 --end_iter 50000
> ```
> 
> ```
> Traceback (most recent call last):
>   File "/home/ml1/FastGAN-pytorch/train_results/test1/eval.py", line 67, in <module>
>     checkpoint = torch.load(ckpt, map_location=lambda a,b: a)
>   File "/home/ml1/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "/home/ml1/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "/home/ml1/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 211, in init
>     super(_open_file, self).init(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: './models/60000.pth'
> ```
> 
> Appears to be a bug. No range check?

check my solution, hope it helps.
